/** The playable characters, and the single source of truth for their keys.
 *
 *  The art is generated by `art/generate_art.py` (see its own `AVATARS` roster), which this
 *  file cannot import — one is Python, the other TypeScript. `tests/avatars.test.ts` closes
 *  that gap by asserting every key here has all four expression PNGs on disk, so adding a
 *  character on one side and forgetting the other fails a test rather than shipping a broken
 *  image URL. */
export const AVATAR_KEYS = ['old_timer', 'card_sharp', 'kid', 'regular'] as const;

export type AvatarKey = (typeof AVATAR_KEYS)[number];

/** The Old-Timer stays the default: he is the single-player opponent, and a player who never
 *  opens the picker should get the character the game has always had. */
export const DEFAULT_AVATAR: AvatarKey = 'old_timer';

/** Shown in the picker. Deliberately descriptive rather than named — these are costumes you
 *  choose, not characters with their own backstories, and naming them would compete with the
 *  display name the player types in right next to it. */
export const AVATAR_LABELS: Record<AvatarKey, string> = {
  old_timer: 'The Old-Timer',
  card_sharp: 'The Card Sharp',
  kid: 'The Kid',
  regular: 'The Regular',
};

export const AVATAR_EXPRESSIONS = ['idle', 'happy', 'rueful', 'blink'] as const;

export function isAvatarKey(value: unknown): value is AvatarKey {
  return typeof value === 'string' && (AVATAR_KEYS as readonly string[]).includes(value);
}

/** Falls back rather than throwing: an unknown key from an older or hand-edited client should
 *  cost that player their costume, not their game. */
export function toAvatarKey(value: unknown): AvatarKey {
  return isAvatarKey(value) ? value : DEFAULT_AVATAR;
}

export function avatarSrc(key: AvatarKey, expression: string): string {
  return `/art/avatar_${key}_${expression}.png`;
}
